url: https://www.civicmapper.com
#baseurl: /

# Site settings
title: CIVICMAPPER
email: info@civicmapper.com
description: ""
corporate:
  name: Civic Mapper LLC
  date: 2018

# lists of things used to generate pages (other than blog, which is default)
collections:
  projects:
    output: true
  sectors:
    output: true

# Build settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
    sass_dir: _sass
    style: compact #[nested, expanded, compact, compressed]