# Clients and Services

title: Services
overview: CivicMapper helps our customers better understand, address, and implement solutions through the use and development of geodata and geospatial technology.
who:
  title: Who We Help
  overview: We help clients in numerous sectors use geospatial data and technology effectively.
how:
  title: How We Help
  overview: We think it makes sense to approach our work in a way that allows room for creative design and problem-solving processes to flourish. To that end, we offer several straightforward and flexible ways to work with you, from fixed-fee project-focused engagements to retainer-based contracts.
  levels:
  - title: Map Shop
    short: Have a project that "needs a map"? That can mean a lot of things! We bring to bear our geospatial technology expertise to create focused digital or paper maps, custom mapping applications, geodatabases for your data, or geospatial analysis tools for your workflows&mdash;any content, format, use, or audience.
    long:
      - We provide general-purpose consulting for civic organizations, bringing our geospatial and subject-area expertise to your organization's individual projects. Our consulting services include
      - <ul><li>geospatial data collection, curation, and maintenance</li><li>web mapping application development and deployment</li><li>spatial and non-spatial data visualization</li><li>strategic planning for geographic information systems (GIS) implementation</li></ul>
      - We emphasize creating mapping solutions and data that have a long life-cycle and are able to serve the organization and the public long after the project ends.
      - We assume there is going to be iteration on these projects, and prefer a "not-to-exceed", flat-fee billing model. It makes for easier budgeting for you, less administration overhead for us, and room for creativity in the work we do for you.
    fa-icon: fa-map
  - title: Virtual Geospatial Technology Officer (vGTO)
    short: When you know that maps and geodata are important to what you do, but you need help. Whether it's choosing technology, building staff technical capacity, executing some project work, or just understanding the landscape of possibilities, we can help. Our vGTO service provides you with a dedicated geospatial technology professional who can help get things up and running in a sustainable way.
    long:
      - ~A dedicated geospatial technology expert available to help you design and implement a geo/data strategy~
    fa-icon: fa-user-plus
  - title: GIS Department-as-a-Service
    short: For teams where developing and executing a long-term geospatial technology strategy is necessary, and/or where active GIS support is needed for an extended period of time (think projects lasting 6+ months), we can provide dedicated geospatial and web technology professionals to help tackle anything. Think of this as having your own dedicated GIS, geospatial, and geo-database development team on-call or in-house.
    long:
      - Our geographic information systems (GIS) department-as-a-service is like having your own dedicated GIS, geospatial, and database development staff in-house.
      - Through an extended-term arrangement, we work side-by-side with you and your team to tackle mapping projects, spin-up data and maps, and even manage your GIS IT infrastructure.
      - By working with you over an extended period, we can help evolve the solutions we build for you.
    fa-icon: fa-users

services-others:
  - title: Data Strategy
    subtitle: Making data the 2nd bullet in your organization's mission
    desc:
      - We help make data a program and process, not just a project; applying the civic tech ethos to your organization
      - Refocusing workflows and business processes to be user and data-centric, but not tech-dependent
      - Leverage OTS technology as needed to keep things simple and cost-effective
    fa-icon: fa-disk
  - title: Mapping Application R&D
    subtitle: Open maps and tools to address common and pressing real-world problems
    desc:
      - In addition to consulting services, we also are also undertaking research and development to build web mapping tools focused on addressing common and pressing problems. We're interested in
      - <ul><li>modeling gray and green stormwater infrastructure performance</li><li>identifying and prioritizing the maintenance of aging infrastructure</li><li>identifying regional economic development opportunities</li><li>mapping natural resource extraction impacts</li><li>evolving mapping technology to support urban design using the GeoDesign framework</li></ul>
      - Keep an eye on <a class="page-scroll" href="#labs">CivicMapper Labs</a> for more information about our R&D efforts.
    fa-icon: fa-cogs